const fs = require('fs');

function replaceStyles(file, newStyles) {
  const content = fs.readFileSync(file, 'utf-8');
  const regex = /const styles = StyleSheet\.create\(\{[\s\S]*?\}\);/g;
  fs.writeFileSync(file, content.replace(regex, newStyles));
  console.log(`${file} updated.`);
}

// 4. LiveScoreboardScreen.js
const lssStyles = `const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    padding: 12,
    paddingTop: 18,
  },
  scrollContent: {
    flex: 1,
  },
  topBar: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 12,
    textAlign: 'center',
  },
  scoreCard: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  matchTitle: {
    color: '#4B5563',
    fontSize: 14,
    marginBottom: 6,
    fontWeight: '600',
  },
  sessionCode: {
    color: '#D97706',
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 8,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  scoreText: {
    color: '#1D4ED8',
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: -1,
  },
  metaText: {
    color: '#6B7280',
    fontSize: 13,
    marginTop: 4,
    fontWeight: '500',
  },
  targetText: {
    color: '#D97706',
    fontSize: 14,
    marginTop: 6,
    fontWeight: '700',
  },
  closedText: {
    color: '#10B981',
    marginTop: 8,
    fontWeight: 'bold',
    fontSize: 14,
  },
  winnerText: {
    color: '#2563EB',
    marginTop: 8,
    fontWeight: '800',
    fontSize: 16,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  infoBlock: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  infoLabel: {
    color: '#9CA3AF',
    fontSize: 12,
    marginBottom: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  infoSubValue: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  playerChipText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  buttonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 12,
  },
  scoreButton: {
    width: '18%',
    minWidth: 58,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  scoreButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  customButton: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    alignItems: 'center',
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.4,
  },
  sectionTitle: {
    color: '#4B5563',
    fontSize: 12,
    marginTop: 8,
    marginBottom: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timelineRow: {
    marginBottom: 16,
    maxHeight: 44,
  },
  timelineBall: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 18,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  wicketBall: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  timelineBallText: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 14,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.7)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  modalTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalList: {
    maxHeight: 340,
  },
  modalOption: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalOptionText: {
    color: '#374151',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalDelete: {
    marginTop: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalDeleteText: {
    color: '#EF4444',
    fontWeight: '700',
    fontSize: 15,
  },
  modalCancel: {
    marginTop: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#4B5563',
    fontWeight: '700',
    fontSize: 15,
  },
  customInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    color: '#111827',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginVertical: 16,
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalConfirm: {
    backgroundColor: '#2563EB',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalConfirmText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});`;
replaceStyles('LiveScoreboardScreen.js', lssStyles);

// 5. MatchViewerScreen.js
const mvsStyles = `const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    padding: 12,
    paddingTop: 18,
  },
  topBar: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
  },
  backButton: {
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 8,
    backgroundColor: '#EFF6FF',
    borderRadius: 8,
    marginTop: 12,
  },
  backText: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '700',
  },
  scrollContent: {
    flex: 1,
  },
  scoreCard: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  sessionCode: {
    color: '#D97706',
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 6,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  matchTitle: {
    color: '#4B5563',
    fontSize: 15,
    marginBottom: 6,
    fontWeight: '600',
  },
  teamLine: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 6,
  },
  bigScore: {
    color: '#1D4ED8',
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: -1,
    marginTop: 4,
  },
  metaText: {
    color: '#6B7280',
    fontSize: 13,
    marginTop: 4,
    fontWeight: '500',
  },
  targetText: {
    color: '#D97706',
    fontSize: 13,
    marginTop: 8,
    fontWeight: '700',
  },
  winnerText: {
    color: '#2563EB',
    marginTop: 8,
    fontWeight: '800',
    fontSize: 16,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  infoBlock: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  infoLabel: {
    color: '#9CA3AF',
    fontSize: 11,
    marginBottom: 6,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoValue: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 2,
  },
  infoSubValue: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  panel: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  panelTitle: {
    color: '#4B5563',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingVertical: 10,
  },
  statName: {
    flex: 1.4,
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  statValue: {
    flex: 1,
    color: '#6B7280',
    fontSize: 13,
    textAlign: 'right',
    fontWeight: '600',
  },
  timelineBall: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 18,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  wicketBall: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  timelineBallText: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 14,
  },
  centerState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  centerText: {
    color: '#6B7280',
    marginTop: 16,
    fontSize: 16,
    fontWeight: '500',
  },
  errorText: {
    color: '#EF4444',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    backgroundColor: '#FEF2F2',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
});`;
replaceStyles('MatchViewerScreen.js', mvsStyles);

